name: Build CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'cli/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cli/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet publish cli/unicli.csproj -c Release -o cli/bin/publish

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: unicli
        path: cli/bin/publish/
